.\"                                      Hey, EMACS: -*- nroff -*-
.TH IBUS-FEP 1 "10 Feb 2012"
.SH NAME
ibus-fep \- IBus client for text terminals
.SH SYNOPSIS
.B ibus-fep
.RI [ options ] [-- commands]
.br
.SH DESCRIPTION
\fBibus-fep\fP is an IBus client for text terminals.
.SH OPTIONS
The \fBibus-fep\fP command follows the usual GNU command line syntax, with
long options starting with two dashes (`-').  A summary of options is
included below.
.TP
.B \-h, \-\-help
Show summary of options.
.TP
.B \-e, \-\-engine=\fIENGINE\fR
Specify engine name.
.SH SEE ALSO
\fBfep\fR(1)
.SH AUTHOR
ibus-fep was written by Daiki Ueno <ueno@unixuser.org>.
